### ISSUE TITLE
Error: 404 Not Found - No Module named CodeChat

### ISSUE THREAD

**Issue by sammcdsam** [bjones1/CodeChat_system#19]
I have followed the steps in the installation instructions, but when I run index.rst from the Codechat_system-Master I get this error. 
Running on Windows 10 with Python 3.9.10

![image](https://user-images.githubusercontent.com/21316952/151715386-4657b8d2-1f93-46cb-bbd0-c4efe2ce661f.png)

The error from the terminal:

Build messages
Loading project file c:\Users\Sam\Documents\CodeChat_system-master\CodeChat_Server\CodeChat_Server\templates\sphinx\codechat_config.yaml.
c:\Users\Sam\Documents\CodeChat_system-master\CodeChat_Server\CodeChat_Server\templates\sphinx > sphinx-build . _build
Running Sphinx v4.4.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python39\lib\site-packages\sphinx\config.py", line 340, in eval_config_file
    exec(code, namespace)
  File "c:\Users\Sam\Documents\CodeChat_system-master\CodeChat_Server\CodeChat_Server\templates\sphinx\conf.py", line 37, in <module>
    import CodeChat.CodeToRest
ModuleNotFoundError: No module named 'CodeChat'

c:\Users\Sam\Documents\CodeChat_system-master\CodeChat_Server\CodeChat_Server\templates\sphinx\index.rst:: ERROR: CodeChat renderer - unable to find the HTML output file c:\Users\Sam\Documents\CodeChat_system-master\CodeChat_Server\CodeChat_Server\templates\sphinx\_build\index.rst.

Terminal showing where codechat_server is installed
![image](https://user-images.githubusercontent.com/21316952/151715524-358f1f31-553d-4e7a-9746-9f6ccb0c6bca.png)

Settings from VsCode
![image](https://user-images.githubusercontent.com/21316952/151715537-267e9f45-2315-4c36-8d7d-66b723e06fb1.png)

**Comment by bjones1** [comment]
Fixes per e-mail conversation by v0.2.2.
