### ISSUE TITLE
Correct formatting for hyperlink 

### ISSUE THREAD

**Issue by LoganJohnson98** [bjones1/CodeChat_system#21]

**Comment by LoganJohnson98** [comment]
# Project Assignment 1:
## Provide a detailed plan that:

Describes the feature you will add.
- Defines which repository/repositories your code will be added to.
- Specifies what libraries, languages, and interfaces your code must work with.
- Details a series of steps you will follow to complete this feature.
- Defines tests to show the feature works correctly.
- Outlines goals for scrum 1 and scrum 2.
###### To Be Completed

**Comment by jpg323** [comment]
We formatted the hyperlink successfully. The hyperlink still doesn't navigate anywhere. The link is created in the code at the bottom of Codechat_Client.js and the function definition is in render_manager.py if you search for "navigate_to_error"

**Comment by jpg323** [comment]
[Here](https://github.com/jpg323/docs/blob/main/Hyperlink%20Documentation.docx?raw=true) is some developer documentation we developed throughout the process to help with turnover and future users.
