### ISSUE TITLE
Notepad ++ Extension

### ISSUE THREAD

**Issue by JoeKenn1118** [bjones1/CodeChat_system#22]
## Feature
Support the Notepad++ text editor and provide similar integration as exists for Visual Studio Code.

## Repositories

1. CodeChat_system, with changes likely confined to the "extensions" subfolder

2. Generate a Notepad++ plugin `.dll` file. optimally, have this file included in the npp-plugins project so installation in Notepad++ can be performed via the menu bar

## Libraries / Languages / Interfaces
Notepad++ is written in C++. While there is support for creating Notepad++ plugins in several languages, such as Ada, C#, D, and Delphi, C++ is most common and what we will be using.

#### Notepad++ Integration
1. Build "Hello World" plugin
2. Explore more advanced plugins that include split-screen functionality, such as MarkdownViewer
3. Create a simple split-screen plugin of our own
4. Create fully-functioning CodeChat plugin.

#### CodeChat Integration
1. Connect NotePad++ plugin to thrift
2. Make html output update every time a new file is opened or the current file is saved.
3. Make html output display in either browser or in split screen
4. Create fully-functioning CodeChat plugin

## Test
1. Have the NotePad++ Plugin create a "Hello World" `.html` file from CodeChat

2. Have the NotePad++ Plugin create a split screen on start-up

3. Have Notepad++ build html output files for multiple file types

   - `.py`
   - `.c` and `.cpp`
   - `.md`
   - `.thrift`
   - etc.

#### Scrum 1
Understand what files, libraries, and tools we will need to complete the project

#### Scrum 2
Create a basic plugin for NotePad++ that can render a file into `.html`

**Comment by bjones1** [comment]
This looks good!
