### ISSUE TITLE
Bootstrap Installer for CodeChat and CodeChat server

### ISSUE THREAD

**Issue by scarbroughzach** [bjones1/CodeChat_system#23]
Austin and I are going to start with the bootstrap installer for Codechat. Taking into consideration the three main OS, Windows, Linux, and MacOS, we want to create a program that downloads the needed files and allocates them to the appropriate folder as if they were being installed manually by the user. The program should require the bare minimum input from the user while also allowing the user to access and use the program files without any confusion by using clear filing implementations. The program will initiate and open the virtual environment used by codechat as to keep the user from having to deal with the clunky command line commands. The command line commands will be entered using a power shell, pre-programming the needed lines to install all needed software. The main language will be python, with possible additions from other languages that are needed as problems arise. Using Pyperclip, we will be able to copy the address of CodeChat from the users command line for ease of transfer. For scrum one, we hope to have atleast 2 of the three main OS's up and running with minimal issue.

**Comment by bjones1** [comment]
A good start; however, please reorganize this so I can clearly see how it addresses all the criteria in the homework. See [this issue](https://github.com/bjones1/CodeChat_system/issues/12#issuecomment-1078627411) for an example.

**Comment by scarbroughzach** [comment]
1.Describes the feature you will add
Our project is developing an installer bootstrap for CodeChat and the CodeChat server. 

2. Defines which repository/repositories your code will be added to
We will be working in the CodeChat_system, as the installer is basically an overhaul of a specific part of the system 
 
3. Specifies what libraries, languages, and interfaces your code must work with
Either python or the power shell language will be our primary, depending on how the path of implementation changes. The only external library it seems will be used is Pyperclip to copy a file path (elaborated on in step 6)

4. Details a series of steps you will follow to complete this feature
The basis of the implementation is to have python installed then automatically enter all command line code. At the moment, as discussed in our team meetings, the plan is to use a power shell for the command line portion. Using these, the user will be asked to download the file package pertaining to their OS, in which the power shell file will install all packages and start the server. We would like to have code that installs python for the user if they do not already have it, but as that's not the main concern of the program, that will be implemented lastly after CodeChat installer itself is finished.

5. Defines tests to show the feature works correctly
The testing will simply be testing if the installer correctly installs CodeChat and its server onto each respective OS properly. We will most likely use a virtual machine to test for Mac and Linux, and an actual windows pc for the windows testing

6. Outlines goals for scrum 1 and scrum 2
For scrum 1, we want to have the base CodeChat and CodeChat server installing successfully on minimum two of the three operating systems. Scrum 2's goal will be errorless installation on all three OS's but with more UI and ease of use improvements, as in the program copying the server's path for the user for the last step of each installation and the installation of python through the program so the user does not need to concern themselves with it.

**Comment by Starnol** [comment]
1. Describes the feature you will add

- Our project is developing an installer bootstrap for CodeChat and the CodeChat server that was passed to us.

2. Defines which repository/repositories your code will be added to
    - Group 1) We will be working in the CodeChat_system, as the installer is basically an overhaul of a specific part of the system 
    - Group 2) Going to keep going with this. 

3. Specifies what libraries, languages, and interfaces your code must work with
   - Group 1) Either python or the power shell language will be our primary, depending on how the path of implementation changes. The only external library it seems will be used is Pyperclip to copy a file path (elaborated on in step 6)
   - Group 2) Not familiar with a power shell language term, so we are going to be using C++ or python depending on the requirements. 

4. Details a series of steps you will follow to complete this feature
   - Group 1) The basis of the implementation is to have python installed then automatically enter all command line code. At the moment, as discussed in our team meetings, the plan is to use a power shell for the command line portion. Using these, the user will be asked to download the file package pertaining to their OS, in which the power shell file will install all packages and start the server. We would like to have code that installs python for the user if they do not already have it, but as that's not the main concern of the program, that will be implemented lastly after CodeChat installer itself is finished.
   - Group 2) Need to know if CodeChat installer was completed if so we can work on the coding to install the most updated python that is compatible with the user system. 

5. Defines tests to show the feature works correctly
   - Group 1) The testing will simply be testing if the installer correctly installs CodeChat and its server onto each respective OS properly. We will most likely use a virtual machine to test for Mac and Linux, and an actual windows pc for the windows testing
   - Group 2) If the installer is in fact working and the python installer is coded, we can test on windows. (We have no MACs or Linux system for us to test those with.) 

6. Outlines goals for scrum 1 and scrum 2
   - Goal before scrum 1 session- Have better understanding where is project stopped at.
   - Goal before scrum 2 session- Have made improvements to the system and have it ready for the next turn over.

**Comment by JoeKenn1118** [comment]
## Features
1. Reduce number of installation steps for Windows and Linux
2. Consider benefits of batch file (Windows) or shell script (Linux) to minimize copy-pasting vs transparency of user being able to see what is being done on their system
3. Fix broken links in Codechat documentation dealing with installation
4. Not install Python automatically/without permission, but provide directions/links to do so.

## Repositories
[CodeChat_system](https://github.com/bjones1/CodeChat_system) (current issue located here)

[CodeChat](https://github.com/bjones1/CodeChat) (? it seems like this should be the likely place for install instructions)

https://codechat-system.readthedocs.io/en/latest/CodeChat_Server/install.html

## Broken Links Re: Installation
https://codechat.readthedocs.io/en/latest/

[Extension Installation Instructions](https://codechat-system.readthedocs.io/en/latest/extensions/contents)

[Not Broken](https://msstate.instructure.com/courses/71820/assignments/668417) but a Canvas assignment shouldn't be the best one-stop resource for CodeChat installation

## Libraries, Languages, Interfaces
### Windows
- Currently in PowerShell script (`.ps1`)
    - Work on resolving error messages
- Look into `.bat` files for use in command line (cmd.exe)
    - Go with whichever is easier to run in an admin environment

### Linux
- BASH (Bourne Again Shell Script)

### MAC
- Unsure on how to implement/test

## Steps

1. Discuss criteria of project
    - [computer skills of target audience](https://www.nngroup.com/articles/computer-skill-levels/)
    - ethics of running unknown/cryptic code vs. convenience
    - alternative/future installation process - what is standard i.e. expected in Windows? Linux?
2. Decide on implementation format
    - updated directions?
    - shell script / batch file?

3. Execute
    - develop scripts
    - write documentation

4. Consider future alternatives
    - (Linux) .deb/.rpm, Software Manager, etc.
    - (Windows) .exe / .zip
    - (Mac) ???

## Tests
Test ease of installation on a variety of machines and users

## Goals
**The installation of CodeChat is more efficient and better documented**

### Scrum 1
Presentation of issues to Dr. Jones and classmates

### Scrum 2
Documentation and scripts complete - request feedback
