### ISSUE TITLE
Sync functionality for the CodeChat system in Visual Studio Code. 

### ISSUE THREAD

**Issue by sammcdsam** [bjones1/CodeChat_system#24]
**Feature:**
Sync functionality for the CodeChat system in Visual Studio Code. 
Feature will allow the user to click parts of the HTML window and be taken to that section of code.

**Libraries:** 
Tre (Github.com/laurikari/tre) - Specifically pull request #49 - Python 3 Bindings (https://github.com/laurikari/tre/pull/49)

andreikop/enki - https://github.com/andreikop/enki
Specifically https://github.com/andreikop/enki/blob/master/enki/plugins/preview/approx_match.py

CodeChat - https://github.com/bjones1/CodeChat_system

**Languages:** 
Python 3

**Sync Functionality Steps:**
Compile Tre Library (Outside of Codechat)
Interface Tre with Python (Pull request)
Reference Regex Matching (Java Script) for heuristic approach

**Scrum Schedule:**
	**Scrum 1 (3/24):**
		Objectives:
Understand Tre Library
Compile Tre library
Review Python 3 PR 
Find out where in the CodeChat repo this feature goes
	**Scrum 2 (3/29):**
		Objectives:
Understand Enki development from Dr.Jones
Match possible ways Python 3 can work in Enki
Begin framework for Sync functionality in Python 3 
Print out possible matches from heuristic search 
Presentation (3/31):
	Demonstrate output of possible matches from heuristic search

**Comment by bjones1** [comment]
This looks good. I look forward to meeting with yall to discuss.
