### ISSUE TITLE
Report failure to generate sageplot when refreshing

### ISSUE THREAD

**Issue by StevenClontz** [bjones1/CodeChat_system#61]
A PreTeXt author just showed me an issue with CodeChat: she made a mistake in her `<sageplot>` that made it unable to generate (she wrote `2x` rather than `2*x`). But CodeChat didn't report any error, so she didn't understand why her image wouldn't "update" when she changed the code.

**Comment by bjones1** [comment]
Thanks for letting me know. By "reporting an error", do you mean the number of errors/warnings reported by the CodeChat GUI? If so, I basically use a regex to search for errors then count these. Given the text of the error (and hopefully, other errors produced by SagePlot), I could redesign the regex. The current version is [here](https://github.com/bjones1/CodeChat_system/blob/master/CodeChat_Server/CodeChat_Server/CodeChat_Client/static/CodeChat_client.js#L364).

**Comment by StevenClontz** [comment]
Hmm. This makes me suspect that perhaps we need to be emitting errors/warnings better from the CLI side. Basically, the idea is that if we `log.warning` or `log.error` in the CLI, CodeChat should already be picking it up, right?

**Comment by bjones1** [comment]
Probably not -- all CodeChat can see is what comes out stdio/stderr, since it runs the CLI as a subprocess then captures those. It only looks at stderr for errors (which is probably where `log.warning/error` sends its output). However, if there's not some standardized way to mark warnings/errors (such as `WARNING: message here`, then my code doesn't have any way to detect it.

Is there any sort of standardized formatting for the warnings/errors reported by pretext and/or the CLI?

**Comment by StevenClontz** [comment]
Working off memory, I think all the `log` stuff is prefixed with `WARNING` or `ERROR` (except for `log.info`).

**Comment by StevenClontz** [comment]
Question: if CodeChat is Python, could you import PreTeXt as a library and use it programmatically rather than a subprocess?

**Comment by bjones1** [comment]
> Question: if CodeChat is Python, could you import PreTeXt as a library and use it programmatically rather than a subprocess?

Probably, but keeping the two processes separate makes life much easier...

**Comment by bjones1** [comment]
> Working off memory, I think all the `log` stuff is prefixed with `WARNING` or `ERROR` (except for `log.info`).

If so, I can definitely look for this in my regex. Samples, especially for Sage, would help me design and test it...

**Comment by StevenClontz** [comment]
As discussed, you can look for STDERR lines that begin with `warning: ` and `error: `.

**Comment by bjones1** [comment]
Thanks! Fixed in a262d3b2.
